### PR TITLE
Mission 2 

### PR DESCRIPTION
**Pull request by Anomandarist**
Mission 2 write up + changes to the formatting of Mission 1 (mostly removed unwanted heading formating)

### CODE REVIEW

**Comment by NightB1ade** [comment]
I think the headings should be there still.  Though, I do agree on dropping them down a heading to at least 3 or more, such that they look similar to that of the downtime bit per person.

**Comment by NightB1ade** [comment]
Though the secondary question is that if Heading 2 is inappropriate and never used, it should be edited in the CSS to be an adequate subheading.

**Comment by Anomandarist** [comment]
I don't particularly want to put the encounters in a heading. I think it breaks up the mission info too much, especially as the notes on an encounter might only be a couple of bullet points. Then, without a heading immediately after the encounter notes they just run on into the rest of the text anyway. So in order to reduce the number of pointless headings I think they should be left at the same size of text as the rest. I don't mind marking them in someway, perhaps in bold or italics?

**Comment by NightB1ade** [comment]
In terms of coding, they definitely should be a heading.  However they can be styled however, I'll put in a provisional Heading 4 that is just only a tiny bit different, from standard text (i.e. a tiny bit bigger).

Bold or Italics on their own should not be used unless doing "strong" indications or "emphasis" indications, which this is neither.  This is a minor heading indication - otherwise it should be another bullet point.  Hence using the ** or __ is inappropriate (in terms of coding).

**Pull request merged**
